#!/bin/bash
set -e

# This script verifies that a standard dnf/yum client can use the generated repository.
# For now, it uses the local repository generated by the integration test.

TEST_REPO_DIR=$(pwd)/test-repo-local

if [ ! -d "$TEST_REPO_DIR/repodata" ]; then
    echo "FAILURE: Local repository not found. Run local_integration_test.sh first."
    exit 1
fi

echo "Starting client validation container..."

docker run --rm \
  -v "$TEST_REPO_DIR":/mnt/repo \
  amazonlinux:2023 /bin/bash -c "
    echo '[local-repo]' > /etc/yum.repos.d/local.repo && \
    echo 'name=Local Repository' >> /etc/yum.repos.d/local.repo && \
    echo 'baseurl=file:///mnt/repo' >> /etc/yum.repos.d/local.repo && \
    echo 'enabled=1' >> /etc/yum.repos.d/local.repo && \
    echo 'gpgcheck=0' >> /etc/yum.repos.d/local.repo && \
    dnf clean all && \
    dnf install -y hello-world && \
    /usr/bin/hello.sh
"

echo "SUCCESS: Client validation completed. The dummy RPM was successfully installed and run."
